/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    services: Service;
    projects: Project;
    news: News;
    jobs: Job;
    team: Team;
    partners: Partner;
    media: Media;
    documents: Document;
    leads: Lead;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('pt' | 'en' | 'es') | ('pt' | 'en' | 'es')[];
  globals: {
    navigation: Navigation;
    footer: Footer;
    contact: Contact;
    social: Social;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    social: SocialSelect<false> | SocialSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'pt' | 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Páginas institucionais montadas com blocos. A página com endereço “inicio” é a home.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?:
    | (
        | HeroBlock
        | StatementBlock
        | ContentBlock
        | MediaTextBlock
        | StatsBlock
        | TimelineBlock
        | GalleryBlock
        | VideoBlock
        | ProjectsBlock
        | ServicesBlock
        | TestimonialsBlock
        | PartnersBlock
        | OdsBlock
        | TeamBlock
        | DownloadsBlock
        | FaqBlock
        | MapBlock
        | ContactFormBlock
        | CtaBlock
      )[]
    | null;
  /**
   * Parte final do endereço da página. Gerado a partir do título; use apenas letras, números e hífens.
   */
  slug: string;
  /**
   * Preenchida automaticamente na primeira publicação.
   */
  publishedAt?: string | null;
  createdBy?: (number | null) | User;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  variant?: ('immersive' | 'image' | 'simple') | null;
  eyebrow?: string | null;
  heading: string;
  lead?: string | null;
  media?: (number | null) | Media;
  links?:
    | {
        type?: ('internal' | 'external') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'projects';
              value: number | Project;
            } | null)
          | ({
              relationTo: 'services';
              value: number | Service;
            } | null)
          | ({
              relationTo: 'news';
              value: number | News;
            } | null);
        url?: string | null;
        label: string;
        appearance?: ('primary' | 'secondary' | 'link') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * Imagens e vídeos. Todo arquivo precisa de texto alternativo (descrição para leitores de tela).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva o que a imagem mostra, como se contasse para alguém que não pode vê-la (ex.: “Jovens plantam mudas na horta comunitária do Bairro Esmeralda, em Atibaia”).
   */
  alt: string;
  caption?: string | null;
  credit?: string | null;
  /**
   * Marcado pela migração quando o alt foi gerado automaticamente.
   */
  needsReview?: boolean | null;
  /**
   * Usada para redirecionar links antigos (/wp-content/uploads/...).
   */
  legacyUrl?: string | null;
  blurDataURL?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Uma ou duas frases. Aparece em listagens, na busca e como descrição padrão para o Google.
   */
  summary?: string | null;
  coverImage: number | Media;
  client?: string | null;
  location?: string | null;
  startYear?: number | null;
  /**
   * Vazio = em andamento
   */
  endYear?: number | null;
  role?: string | null;
  partners?: (number | Partner)[] | null;
  services?: (number | Service)[] | null;
  ods?:
    | ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12' | '13' | '14' | '15' | '16' | '17')[]
    | null;
  /**
   * Opcional. Copie latitude e longitude do Google Maps (clique com o botão direito no local).
   */
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  featured?: boolean | null;
  accent?: ('blue' | 'green' | 'dark') | null;
  /**
   * Somente números comprovados (relatórios, prestação de contas).
   */
  highlights?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Monte a narrativa do case intercalando textos, imagens, números, vídeos e citações.
   */
  chapters?:
    | (
        | ContentBlock
        | MediaTextBlock
        | StatementBlock
        | StatsBlock
        | GalleryBlock
        | VideoBlock
        | TimelineBlock
        | TestimonialsBlock
        | OdsBlock
      )[]
    | null;
  quote?: {
    text?: string | null;
    source?: string | null;
  };
  publications?:
    | {
        label: string;
        url: string;
        cover?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  video?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * Parte final do endereço da página. Gerado a partir do título; use apenas letras, números e hífens.
   */
  slug: string;
  /**
   * Preenchida automaticamente na primeira publicação.
   */
  publishedAt?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  fullName?: string | null;
  kind?: ('client' | 'partner' | 'executor') | null;
  logo?: (number | null) | Media;
  url?: string | null;
  showOnHome?: boolean | null;
  /**
   * Números menores aparecem primeiro.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Uma ou duas frases. Aparece em listagens, na busca e como descrição padrão para o Google.
   */
  summary?: string | null;
  icon?: ('territory' | 'heritage' | 'education' | 'management' | 'diffusion') | null;
  coverImage?: (number | null) | Media;
  deliverables?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  layout?:
    | (
        | HeroBlock
        | StatementBlock
        | ContentBlock
        | MediaTextBlock
        | StatsBlock
        | TimelineBlock
        | GalleryBlock
        | VideoBlock
        | ProjectsBlock
        | ServicesBlock
        | TestimonialsBlock
        | PartnersBlock
        | OdsBlock
        | TeamBlock
        | DownloadsBlock
        | FaqBlock
        | MapBlock
        | ContactFormBlock
        | CtaBlock
      )[]
    | null;
  /**
   * Parte final do endereço da página. Gerado a partir do título; use apenas letras, números e hífens.
   */
  slug: string;
  /**
   * Números menores aparecem primeiro.
   */
  order?: number | null;
  /**
   * Preenchida automaticamente na primeira publicação.
   */
  publishedAt?: string | null;
  createdBy?: (number | null) | User;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock".
 */
export interface StatementBlock {
  eyebrow?: string | null;
  /**
   * Texto grande que se revela conforme a rolagem. Ideal para manifestos e missão.
   */
  text: string;
  links?:
    | {
        type?: ('internal' | 'external') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'projects';
              value: number | Project;
            } | null)
          | ({
              relationTo: 'services';
              value: number | Service;
            } | null)
          | ({
              relationTo: 'news';
              value: number | News;
            } | null);
        url?: string | null;
        label: string;
        appearance?: ('primary' | 'secondary' | 'link') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Uma ou duas frases. Aparece em listagens, na busca e como descrição padrão para o Google.
   */
  summary?: string | null;
  coverImage: number | Media;
  category?: ('noticia' | 'artigo' | 'evento' | 'publicacao') | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedProjects?: (number | Project)[] | null;
  /**
   * Parte final do endereço da página. Gerado a partir do título; use apenas letras, números e hífens.
   */
  slug: string;
  /**
   * Preenchida automaticamente na primeira publicação.
   */
  publishedAt?: string | null;
  createdBy?: (number | null) | User;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Administrador: tudo, inclusive usuários e configurações. Editor: cria, edita e publica conteúdo. Autor: cria rascunhos de notícias e projetos para revisão.
   */
  roles: ('admin' | 'editor' | 'author')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  eyebrow?: string | null;
  heading?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  layout?: ('split' | 'narrow') | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaTextBlock".
 */
export interface MediaTextBlock {
  eyebrow?: string | null;
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media: number | Media;
  mediaPosition?: ('right' | 'left') | null;
  links?:
    | {
        type?: ('internal' | 'external') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'projects';
              value: number | Project;
            } | null)
          | ({
              relationTo: 'services';
              value: number | Service;
            } | null)
          | ({
              relationTo: 'news';
              value: number | News;
            } | null);
        url?: string | null;
        label: string;
        appearance?: ('primary' | 'secondary' | 'link') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * Use apenas números comprovados e informe a fonte/período no contexto.
   */
  items?:
    | {
        value: string;
        label: string;
        context?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        period: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  eyebrow?: string | null;
  heading?: string | null;
  images: (number | Media)[];
  layout?: ('mosaic' | 'carousel') | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  eyebrow?: string | null;
  heading?: string | null;
  source?: ('upload' | 'embed') | null;
  file?: (number | null) | Media;
  url?: string | null;
  poster?: (number | null) | Media;
  caption?: string | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsBlock".
 */
export interface ProjectsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  mode?: ('featured' | 'latest' | 'selected') | null;
  selected?: (number | Project)[] | null;
  limit?: number | null;
  showAllLink?: boolean | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projects';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  services?: (number | Service)[] | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * Publique apenas depoimentos autorizados por escrito.
   */
  items?:
    | {
        quote: string;
        author?: string | null;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock".
 */
export interface PartnersBlock {
  eyebrow?: string | null;
  heading?: string | null;
  partners?: (number | Partner)[] | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partners';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OdsBlock".
 */
export interface OdsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  text?: string | null;
  goals?:
    | ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12' | '13' | '14' | '15' | '16' | '17')[]
    | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ods';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock".
 */
export interface TeamBlock {
  eyebrow?: string | null;
  heading?: string | null;
  members?: (number | Team)[] | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  bio?: string | null;
  linkedin?: string | null;
  lattes?: string | null;
  /**
   * Números menores aparecem primeiro.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DownloadsBlock".
 */
export interface DownloadsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  documents?: (number | Document)[] | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'downloads';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  description?: string | null;
  category?: ('publicacao' | 'relatorio' | 'institucional' | 'edital') | null;
  /**
   * Números menores aparecem primeiro.
   */
  order?: number | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlock".
 */
export interface MapBlock {
  eyebrow?: string | null;
  heading?: string | null;
  address?: string | null;
  lat: number;
  lng: number;
  zoom?: number | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'map';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  /**
   * Permite linkar direto para a seção, ex.: #metodologia. Use letras minúsculas e hífens.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  heading: string;
  text?: string | null;
  links?:
    | {
        type?: ('internal' | 'external') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'projects';
              value: number | Project;
            } | null)
          | ({
              relationTo: 'services';
              value: number | Service;
            } | null)
          | ({
              relationTo: 'news';
              value: number | News;
            } | null);
        url?: string | null;
        label: string;
        appearance?: ('primary' | 'secondary' | 'link') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * As cores seguem a marca. Textos e botões se ajustam automaticamente para manter o contraste.
   */
  tone?: ('default' | 'alt' | 'brand' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  /**
   * Uma ou duas frases. Aparece em listagens, na busca e como descrição padrão para o Google.
   */
  summary?: string | null;
  type?: ('clt' | 'pj' | 'estagio' | 'temporario') | null;
  location?: string | null;
  opening?: ('open' | 'closed') | null;
  closingDate?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Ex.: mailto:contato@quarau.com.br?subject=Vaga ou link de formulário externo.
   */
  applyUrl: string;
  /**
   * Parte final do endereço da página. Gerado a partir do título; use apenas letras, números e hífens.
   */
  slug: string;
  /**
   * Preenchida automaticamente na primeira publicação.
   */
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mensagens enviadas pelo formulário do site. Dados pessoais: trate conforme a LGPD.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  organization?: string | null;
  subject?: string | null;
  message: string;
  status?: ('new' | 'in_progress' | 'answered' | 'archived') | null;
  notes?: string | null;
  meta?: {
    consent?: boolean | null;
    sourcePath?: string | null;
    locale?: string | null;
    ipHash?: string | null;
    userAgent?: string | null;
    emailDelivered?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'news';
          value: number | News;
        } | null);
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        statement?: T | StatementBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaText?: T | MediaTextBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        projects?: T | ProjectsBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        partners?: T | PartnersBlockSelect<T>;
        ods?: T | OdsBlockSelect<T>;
        team?: T | TeamBlockSelect<T>;
        downloads?: T | DownloadsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        map?: T | MapBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
      };
  slug?: T;
  publishedAt?: T;
  createdBy?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  lead?: T;
  media?: T;
  links?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock_select".
 */
export interface StatementBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  text?: T;
  links?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        id?: T;
      };
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  layout?: T;
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaTextBlock_select".
 */
export interface MediaTextBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  media?: T;
  mediaPosition?: T;
  links?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        id?: T;
      };
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        context?: T;
        id?: T;
      };
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        period?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  images?: T;
  layout?: T;
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  source?: T;
  file?: T;
  url?: T;
  poster?: T;
  caption?: T;
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsBlock_select".
 */
export interface ProjectsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  mode?: T;
  selected?: T;
  limit?: T;
  showAllLink?: T;
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  services?: T;
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        id?: T;
      };
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock_select".
 */
export interface PartnersBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  partners?: T;
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OdsBlock_select".
 */
export interface OdsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  text?: T;
  goals?: T;
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock_select".
 */
export interface TeamBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  members?: T;
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DownloadsBlock_select".
 */
export interface DownloadsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  documents?: T;
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlock_select".
 */
export interface MapBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  address?: T;
  lat?: T;
  lng?: T;
  zoom?: T;
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  links?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        id?: T;
      };
  tone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  icon?: T;
  coverImage?: T;
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  body?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        statement?: T | StatementBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaText?: T | MediaTextBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        projects?: T | ProjectsBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        partners?: T | PartnersBlockSelect<T>;
        ods?: T | OdsBlockSelect<T>;
        team?: T | TeamBlockSelect<T>;
        downloads?: T | DownloadsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        map?: T | MapBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
      };
  slug?: T;
  order?: T;
  publishedAt?: T;
  createdBy?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  coverImage?: T;
  client?: T;
  location?: T;
  startYear?: T;
  endYear?: T;
  role?: T;
  partners?: T;
  services?: T;
  ods?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  featured?: T;
  accent?: T;
  highlights?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  body?: T;
  chapters?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
        mediaText?: T | MediaTextBlockSelect<T>;
        statement?: T | StatementBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        ods?: T | OdsBlockSelect<T>;
      };
  quote?:
    | T
    | {
        text?: T;
        source?: T;
      };
  publications?:
    | T
    | {
        label?: T;
        url?: T;
        cover?: T;
        id?: T;
      };
  video?: T;
  gallery?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  publishedAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  coverImage?: T;
  category?: T;
  body?: T;
  relatedProjects?: T;
  slug?: T;
  publishedAt?: T;
  createdBy?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  type?: T;
  location?: T;
  opening?: T;
  closingDate?: T;
  description?: T;
  applyUrl?: T;
  slug?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  linkedin?: T;
  lattes?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  fullName?: T;
  kind?: T;
  logo?: T;
  url?: T;
  showOnHome?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  needsReview?: T;
  legacyUrl?: T;
  blurDataURL?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  order?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  organization?: T;
  subject?: T;
  message?: T;
  status?: T;
  notes?: T;
  meta?:
    | T
    | {
        consent?: T;
        sourcePath?: T;
        locale?: T;
        ipHash?: T;
        userAgent?: T;
        emailDelivered?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Até 7 itens para manter o menu legível.
   */
  items?:
    | {
        type?: ('internal' | 'external') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'projects';
              value: number | Project;
            } | null)
          | ({
              relationTo: 'services';
              value: number | Service;
            } | null)
          | ({
              relationTo: 'news';
              value: number | News;
            } | null);
        url?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Deixe o texto vazio para não exibir o botão.
   */
  cta?: {
    type?: ('internal' | 'external') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'news';
          value: number | News;
        } | null);
    url?: string | null;
    label?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              reference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'projects';
                    value: number | Project;
                  } | null)
                | ({
                    relationTo: 'services';
                    value: number | Service;
                  } | null)
                | ({
                    relationTo: 'news';
                    value: number | News;
                  } | null);
              url?: string | null;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        type?: ('internal' | 'external') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'projects';
              value: number | Project;
            } | null)
          | ({
              relationTo: 'services';
              value: number | Service;
            } | null)
          | ({
              relationTo: 'news';
              value: number | News;
            } | null);
        url?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  companyName?: string | null;
  cnpj?: string | null;
  email: string;
  phones?:
    | {
        number: string;
        whatsapp?: boolean | null;
        id?: string | null;
      }[]
    | null;
  address?: {
    street?: string | null;
    district?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    lat?: number | null;
    lng?: number | null;
  };
  hours?: string | null;
  formSubjects?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * E-mails separados por vírgula. Vazio = e-mail principal.
   */
  notificationEmails?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social".
 */
export interface Social {
  id: number;
  profiles?:
    | {
        network: 'instagram' | 'linkedin' | 'facebook' | 'youtube' | 'whatsapp';
        url: string;
        handle?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * %s é substituído pelo título de cada página.
   */
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  organization?: {
    legalName?: string | null;
    foundingYear?: number | null;
    areaServed?: string | null;
  };
  analytics?: {
    umamiWebsiteId?: string | null;
    umamiScriptUrl?: string | null;
  };
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: {
      type?: ('internal' | 'external') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'projects';
            value: number | Project;
          } | null)
        | ({
            relationTo: 'services';
            value: number | Service;
          } | null)
        | ({
            relationTo: 'news';
            value: number | News;
          } | null);
      url?: string | null;
      label?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  companyName?: T;
  cnpj?: T;
  email?: T;
  phones?:
    | T
    | {
        number?: T;
        whatsapp?: T;
        id?: T;
      };
  address?:
    | T
    | {
        street?: T;
        district?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        lat?: T;
        lng?: T;
      };
  hours?: T;
  formSubjects?:
    | T
    | {
        label?: T;
        id?: T;
      };
  notificationEmails?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social_select".
 */
export interface SocialSelect<T extends boolean = true> {
  profiles?:
    | T
    | {
        network?: T;
        url?: T;
        handle?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  defaultOgImage?: T;
  organization?:
    | T
    | {
        legalName?: T;
        foundingYear?: T;
        areaServed?: T;
      };
  analytics?:
    | T
    | {
        umamiWebsiteId?: T;
        umamiScriptUrl?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null)
      | ({
          relationTo: 'news';
          value: number | News;
        } | null)
      | ({
          relationTo: 'jobs';
          value: number | Job;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}